In [6]:
#pacote para operações matematicas
import numpy as np
a = np.array([1,2,3])

In [7]:
print(a)

[1 2 3]


In [9]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
c = np.eye(4)

In [15]:
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
b.std()

2.581988897471611